"""
Clawzd — App Code Validator.

Validates HTML, CSS, and JavaScript files generated by the LLM
before they are published as live mini-apps.

Validation layers:
  - HTML: structure checks (DOCTYPE, <html>, <head>, <body>), tag balance
  - CSS:  brace balance, empty rule detection, common syntax errors
  - JS:   Node.js --check syntax validation (subprocess), brace/paren balance fallback
"""
import logging
import os
import re
import subprocess
import tempfile
from html.parser import HTMLParser
from typing import Optional

logger = logging.getLogger("clawzd.app_validator")


# ---------------------------------------------------------------------------
# HTML Validation
# ---------------------------------------------------------------------------

class _HtmlChecker(HTMLParser):
    """Lightweight HTML tag-balance checker."""

    def __init__(self):
        super().__init__()
        self.errors: list[str] = []
        self.warnings: list[str] = []
        self._stack: list[str] = []
        # Self-closing tags that don't need a closing counterpart
        self._void = frozenset({
            "area", "base", "br", "col", "embed", "hr", "img", "input",
            "link", "meta", "param", "source", "track", "wbr",
        })

    def handle_starttag(self, tag: str, attrs):
        tag = tag.lower()
        if tag not in self._void:
            self._stack.append(tag)

    def handle_endtag(self, tag: str):
        tag = tag.lower()
        if tag in self._void:
            return
        if not self._stack:
            self.errors.append(f"Unexpected closing tag </{tag}> with no matching opening tag")
            return
        if self._stack[-1] == tag:
            self._stack.pop()
        else:
            # Try to find the tag further up the stack (tolerate mild mis-nesting)
            for i in range(len(self._stack) - 1, -1, -1):
                if self._stack[i] == tag:
                    unclosed = self._stack[i + 1:]
                    if unclosed:
                        self.errors.append(
                            f"Unclosed <{', '.join(unclosed)}> before </{tag}>"
                        )
                    self._stack = self._stack[:i]
                    return
            self.errors.append(f"Closing </{tag}> has no matching opening tag")

    def get_unclosed(self) -> list[str]:
        return list(self._stack)


def validate_html(content: str, filename: str = "index.html") -> list[str]:
    """Validate HTML content. Returns a list of error strings (empty = OK)."""
    errors = []

    if not content or not content.strip():
        errors.append(f"{filename}: HTML file is empty")
        return errors

    # Structure checks (only for main index.html)
    if filename == "index.html":
        lower = content.lower()
        if "<!doctype" not in lower:
            errors.append(f"{filename}: Missing <!DOCTYPE html> declaration")
        if "<html" not in lower:
            errors.append(f"{filename}: Missing <html> tag")
        if "<head" not in lower:
            errors.append(f"{filename}: Missing <head> tag")
        if "<body" not in lower:
            errors.append(f"{filename}: Missing <body> tag")

    # Tag balance
    checker = _HtmlChecker()
    try:
        checker.feed(content)
    except Exception as e:
        errors.append(f"{filename}: HTML parse error: {e}")
        return errors

    unclosed = checker.get_unclosed()
    if unclosed:
        errors.append(f"{filename}: Unclosed HTML tags: <{', '.join(unclosed)}>")

    errors.extend(f"{filename}: {e}" for e in checker.errors)

    return errors


# ---------------------------------------------------------------------------
# CSS Validation
# ---------------------------------------------------------------------------

def validate_css(content: str, filename: str = "style.css") -> list[str]:
    """Validate CSS content. Returns a list of error strings (empty = OK)."""
    errors = []

    if not content or not content.strip():
        # Empty CSS is acceptable (template might not need styles)
        return errors

    # Strip comments before analysis
    stripped = re.sub(r'/\*[\s\S]*?\*/', '', content)
    # Strip string literals to avoid false positives on braces inside strings
    stripped = re.sub(r'"[^"]*"', '""', stripped)
    stripped = re.sub(r"'[^']*'", "''", stripped)

    # Brace balance
    open_count = stripped.count('{')
    close_count = stripped.count('}')
    if open_count != close_count:
        diff = open_count - close_count
        if diff > 0:
            errors.append(f"{filename}: {diff} unclosed '{{' brace(s) in CSS")
        else:
            errors.append(f"{filename}: {-diff} extra '}}' brace(s) in CSS")

    # Empty rule detection (non-critical but worth flagging)
    empty_rules = re.findall(r'[^{]+\{\s*\}', stripped)
    if len(empty_rules) > 5:
        # Only warn if there are many — a few empty rules are OK
        pass  # Not an error, just style

    # Common typos: missing colon in property declarations
    # Look for lines like "  color red;" (missing colon)
    lines = stripped.split('\n')
    for i, line in enumerate(lines, 1):
        line = line.strip()
        if not line or line.startswith(('/', '*', '@', '}', '{')) or line.endswith('{'):
            continue
        # Inside a rule, properties should have a colon
        if ';' in line and ':' not in line and '{' not in line and '}' not in line:
            # Might be a property missing its colon
            errors.append(f"{filename}:{i}: Possible missing ':' in CSS property: {line[:60]}")

    return errors


# ---------------------------------------------------------------------------
# JavaScript Validation
# ---------------------------------------------------------------------------

def validate_js(content: str, filename: str = "app.js") -> list[str]:
    """Validate JavaScript content. Returns a list of error strings (empty = OK).

    Uses Node.js --check for syntax validation when available,
    falls back to brace/paren balance checks.
    """
    errors = []

    if not content or not content.strip():
        # Empty JS is acceptable
        return errors

    # Try Node.js syntax check first (most reliable)
    node_errors = _node_syntax_check(content, filename)
    if node_errors is not None:
        return node_errors

    # Fallback: basic structural checks
    errors.extend(_js_balance_check(content, filename))

    return errors


def _node_syntax_check(content: str, filename: str) -> Optional[list[str]]:
    """Run Node.js --check on the content. Returns errors or None if Node unavailable."""
    try:
        with tempfile.NamedTemporaryFile(
            mode='w', suffix='.js', delete=False, encoding='utf-8'
        ) as f:
            f.write(content)
            tmp_path = f.name

        result = subprocess.run(
            ['node', '--check', tmp_path],
            capture_output=True, text=True, timeout=10,
        )

        if result.returncode != 0:
            # Parse Node error output
            stderr = result.stderr.strip()
            # Clean up temp file paths in error messages
            stderr = stderr.replace(tmp_path, filename)
            # Extract the most useful line(s)
            lines = stderr.split('\n')
            errors = []
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                if line.startswith('^'):
                    continue  # Skip pointer lines
                if 'SyntaxError' in line or filename in line:
                    errors.append(f"{filename}: {line}")
                elif line and not errors:
                    errors.append(f"{filename}: JS syntax error: {line}")
            return errors if errors else [f"{filename}: JavaScript syntax error"]

        return []  # Valid JS

    except FileNotFoundError:
        logger.debug("Node.js not available for JS validation")
        return None  # Node not available
    except subprocess.TimeoutExpired:
        logger.warning("Node.js syntax check timed out for %s", filename)
        return None
    except Exception as e:
        logger.debug("Node.js check failed: %s", e)
        return None
    finally:
        try:
            os.unlink(tmp_path)
        except (NameError, OSError):
            pass


def _js_balance_check(content: str, filename: str) -> list[str]:
    """Fallback JS validation: check brace/paren/bracket balance."""
    errors = []

    # Strip comments and strings to avoid false positives
    stripped = re.sub(r'//[^\n]*', '', content)
    stripped = re.sub(r'/\*[\s\S]*?\*/', '', stripped)
    stripped = re.sub(r'"(?:[^"\\]|\\.)*"', '""', stripped)
    stripped = re.sub(r"'(?:[^'\\]|\\.)*'", "''", stripped)
    stripped = re.sub(r'`(?:[^`\\]|\\.)*`', '``', stripped)

    pairs = {'{': '}', '(': ')', '[': ']'}
    stack = []
    for ch in stripped:
        if ch in pairs:
            stack.append(ch)
        elif ch in pairs.values():
            if not stack:
                errors.append(f"{filename}: Extra closing '{ch}' in JavaScript")
                break
            expected = pairs[stack[-1]]
            if ch != expected:
                errors.append(
                    f"{filename}: Mismatched brackets: expected '{expected}' but got '{ch}'"
                )
                break
            stack.pop()

    if stack and not errors:
        unclosed = [pairs[ch] for ch in stack]
        errors.append(f"{filename}: Unclosed brackets in JavaScript: {''.join(unclosed[:5])}")

    return errors


# ---------------------------------------------------------------------------
# Combined Validator
# ---------------------------------------------------------------------------

def validate_app_files(files: dict[str, str]) -> dict:
    """Validate all files in an app bundle.

    Args:
        files: Dict of filename → content.

    Returns:
        {
            "valid": bool,
            "errors": list[str],     # blocking issues
            "warnings": list[str],   # non-blocking issues
        }
    """
    all_errors = []
    all_warnings = []

    for filename, content in files.items():
        safe_name = os.path.basename(filename).lower()

        if safe_name.endswith(('.html', '.htm')):
            errs = validate_html(content, safe_name)
            all_errors.extend(errs)

        elif safe_name.endswith('.css'):
            errs = validate_css(content, safe_name)
            all_errors.extend(errs)

        elif safe_name.endswith('.js'):
            errs = validate_js(content, safe_name)
            all_errors.extend(errs)

        # Check for completely empty files (likely generation error)
        if content is not None and not content.strip() and safe_name == "index.html":
            all_errors.append(f"{safe_name}: File is empty")

    return {
        "valid": len(all_errors) == 0,
        "errors": all_errors,
        "warnings": all_warnings,
    }
